# Dockerfile.vosk
FROM python:3.10-slim

# Instal·la dependències del sistema i FFmpeg per a conversió automàtica d'àudio
RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*

# Instal·la la llibreria VOSK
RUN pip install vosk

WORKDIR /app

CMD ["tail", "-f", "/dev/null"]
